# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tibco-Rv
version:      1.11
version_from: Rv.pm
installdirs:  site
requires:
    Inline:                        0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
